name: Build And Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ngx-admin

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            cuongnew87/ngx-admin:latest
            cuongnew87/ngx-admin:${{ github.run_number }}
